src/rulerewriters.jl
src/simplify.jl
src/symbolic.jl

Closes https://github.com/shashi/SymbolicUtils.jl/issues/17
In the process of writing this, I noticed some problems with the way `flatten_term` and `sort_args` were implemented (always convert ed output symtype to `Number`) so I took the liberty of fixing that as well. 
Can be factored into a separate PR if desired.

Remove Type Storage

---

src/methods.jl
src/rulesets.jl
src/simplify.jl
src/symbolic.jl

This should allow MTK and others to call `simplify` by defining 3 tiny accessor methods.
This is what @MasonProtter and I agreed on in a discussion today. To summarize:
1. This seems to be the shortest path to getting MTK to work with this right away even forgetting all the idiosyncratic differences. (the conversion should be cheap, we construct the whole tree several times during a `simplify` so this is no big deal).
2. work on the tracing analysis in can be done on this in a separate package without Symbolic <: Numeric decisions
3. Mike Innes wanted to use the rules system on Mjolnir IR, which should become possible with this.

WIP Interface for `simplify`

---

README.md
src/SymbolicUtils.jl
src/methods.jl
src/rule_dsl.jl
src/simplify.jl
src/types.jl
test/basics.jl
test/fuzz.jl
test/interface.jl
test/order.jl
test/rewrite.jl
test/rulesets.jl

I noticed we have to say "symbolic variable" to refer to... symbols. Variable is an overloaded term anyway.

Variable, vars -> Sym, syms

---

Project.toml
test/rulesets.jl

This adds a test-set where we apply this to a bunch of expressions:
```julia
R1 = RuleSet(SymbolicUtils.SIMPLIFY_RULES)
R2 = RuleSet(shuffle(R1.rules))
R1(ex) == R1(R2(ex))
```
the idea is that apply rules in a random order and then simplifying using the standard order should be the same as just simplifying with the standard order. 
This might be better suited to being done in the fuzzer, but I didn't really understand the fuzzer very well.

add shuffle rules

---

Project.toml
src/rule_dsl.jl
src/rulesets.jl
src/simplify.jl
test/interface.jl
test/rulesets.jl
test/runtests.jl

Okay, this changes how we do simplification. Instead of one big, `RuleSet` which is applied, this uses nested rulesets to determine which rules actually get applied. In theory, this should be more efficient than our current system once we have more rules, but I find that currently it's a couple percent slower on this benchmark compared to master:
```julia
using SymbolicUtils, Random
Random.seed!(1)
let
@syms a b c d
expr1 = foldr((x,y)->rand([*, /, +])(x,y), rand([a,b,c,d,1,2], 20))
SymbolicUtils.@timerewrite simplify(expr1)
end
```
(note that you have to run it like 3 times to get compilation out of the way).
I'll write up a more detailed report of what I changed and why in a bit.

Simplify rules refactor

---

Project.toml
benchmark/benchmarks.jl
src/matchers.jl
src/rule_dsl.jl
src/simplify.jl
src/util.jl
test/runtests.jl

```
Benchmarkresults:
Package: /home/shashi/.julia/dev/SymbolicUtils
Date: 2 May 2020 - 10:16
Package commit: c62477
Julia commit: 381693
BenchmarkGroup:
6-element BenchmarkTools.BenchmarkGroup:
tags: []
"rule:noop:Sym" => Trial(34.001 ns)
"rule:noop:Int" => Trial(21.444 ns)
"ruleset:noop:Term" => Trial(2.823 μs)
"ruleset:noop:Int" => Trial(0.024 ns)
"ruleset:noop:Sym" => Trial(139.023 ns)
"rule:noop:Term" => Trial(495.682 ns)
```
Will post comparison vs master soon. ImmutableDict is much faster it turns out.

Simple benchmark script

---

src/matchers.jl
src/rule_dsl.jl
src/simplify.jl
test/basics.jl
test/rulesets.jl

This `@CTX` syntax is useful for #67 
```julia
@rule(~x::Contextual((x, ctx) -> ctx==EmptyCtx()) => "yes")(1) == "yes"
@rule(~x::Contextual((x, ctx) -> haskey(ctx, x)) => true)(a, Dict(a=>1))
@rule(~x::Contextual((x, ctx) -> haskey(ctx, x)) => true)(b, Dict(a=>1)) === nothing
@rule(~x => @ctx)(a, "test") == "test"
@rule(~x::Contextual((x, ctx) -> haskey(ctx, x)) => (@ctx)[~x])(a, Dict(a=>1)) === 1
@rule(~x::Contextual((x, ctx) -> haskey(ctx, x)) => (@ctx)[~x])(b, Dict(a=>1)) === nothing
```

Pass around a context object from simplify to matchers and rewriters

---

src/SymbolicUtils.jl
src/methods.jl
src/rulesets.jl
src/simplify.jl
src/types.jl
test/basics.jl
test/interface.jl
test/rewrite.jl
test/rulesets.jl
test/runtests.jl

Added some boolean algebra rules.
`cond` is like `ifelse`. Unfortunately `ifelse` itself is not a generic function.
```julia
julia>@syms a::Real
julia> simplify(substitute(cond(a < 0, -a,a), Dict(a=>-1)))
-1
```
closes #67

boolean methods and rules

---

src/methods.jl
src/rulesets.jl
test/fuzzlib.jl
test/rulesets.jl

ModelingToolkit keeps these around after applying DiffRules rules.
closes #81

Simplify one and zero terms

---

.travis.yml
Project.toml
benchmark/benchmarks.jl
src/SymbolicUtils.jl
src/rule_dsl.jl
src/simplify.jl
test/benchmark.jl
test/fuzz.jl
test/rulesets.jl

Okay, so this "works", but it's a bit tricky to actually generate a an expression where it's worth doing. You need really big, deep terms and they can't be too 'lopsided', i.e. `(x + y) + (z + w)` is preferred to `(x + (y + (z + w)))` because it provides more opportunities for worthwhile task spawning. 
Here's something that I suspect is a bit of a 'best case' scenario. I'm using `Transducers` here to make expressions because it's `reduce` won't generate lopsided terms, unlike `foldl`. 
```julia
julia> using SymbolicUtils, Transducers
julia> begin 
function generate_random_term(length)
reduce(Map(_ -> rand([a,b,c,d,1,2])), 1:length, basesize=0, init=0) do x, y
x, y = rand(Bool) ? (x, y) : (y, x)
rand([*, +, /])(x, y)
end
end
@syms a b c d
expr1 = generate_random_term(1500)
print("Threaded …
```

Multithreaded rules application

---

src/rule.jl
test/runtests.jl

Fixes #114 
Tiny change to fix unbound parameter.
Still fails `isempty(detect_unbound_args(SymbolicUtils))` due to weird unbound parameter in AbstractAlgebra.
Might want to include explict test.  I've included a commit with that test (`@test_broken`, for now, and probably for the foreseeable future, due to the dependence on upstream compliance), but you can easily remove that commit if desired.

Remove unbound parameter

---

docs/api.md
docs/interface.md
src/SymbolicUtils.jl
src/abstractalgebra.jl
src/api.jl
src/matchers.jl
src/ordering.jl
src/rewriters.jl
src/rule.jl
src/simplify_rules.jl
src/types.jl
src/utils.jl
test/interface.jl

use interface on the matched expression instead of requiring it to be a `Term`

---

src/types.jl

With this,
```julia
julia> @btime hash($(a+1))
105.839 ns (5 allocations: 80 bytes)
0xba5e19c850a1204d
```
Without this,
```julia
julia> @btime hash($(a+1))
506.854 ns (10 allocations: 192 bytes)
0xe566d1194511d3f0
```

speed up hash on Term

---

src/methods.jl

In https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/134#issuecomment-721700399, it was pointed out that the error message points to `isnumberlike` instead of `islike`. Closes #134

fix error message in assertlike

---

src/abstractalgebra.jl
src/methods.jl
src/simplify_rules.jl

Should accomplish the goal "make sure inv does not get introduced, only negative powers do." in https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/133
I also made a random `global` I noticed a `global const`. Does `MPOLY_CLEANUP` even need to be a `global`, or can it just be internal?

Convert `inv` to literal pow

---

src/methods.jl

This fixes a problem with the way I did the previous PR
Before:
```julia
julia> x ^ -1
(x ^ -1) ^ 1
```
after
```julia
julia> x ^ -1
x ^ -1
```

handle literal_pow

---

src/methods.jl
src/types.jl

We need `symtype(similarterm(f, args...)) === symtype(f(args...))` to
make sure that terms constructed by substitution are the same as terms
constructed by evaluation.
This PR also fixes `isequal(::Add, ::Symbolic)`-like checks.

Terms constructed by substitution should be the same as terms constructed by evaluation

---

src/types.jl

Since SymbolicUtils puns on julia's syntax, it should probably use the Julia
symbol printer to make sure that non-identifier symbols can be entered back.
Before:
```
julia> @syms var"f(x)"
(f(x),)
```
After:
```
julia> @syms var"f(x)"
(var"f(x)",)
```

Switch Sym printer to use Julia's syntax printer

---

src/types.jl

This tiny PR just changes
```julia
symtype(x) = Any
```
to
```julia
symtype(x) = typeof(x)
```
The current implementation leads to a loss of type information for many non-symbolic values. This propagates up the tree, leading to lots of expressions erroneously being considered `::Any`

default to symtype(x) = typeof(x)

---

Project.toml

Soss has some dependencies that haven't yet updated their `StaticArrays` compat to 1.0. Could we loosen this a little?

Allow StaticArrays 0.12

---

src/code.jl
test/code.jl

This allows use of some hacks to make threaded expressions work inside RuntimeGeneratedFunctions.

make SpawnFetch take Func expressions and arguments

---

README.md
page/_layout/page_foot.html
page/index.md

Hi, I've decided to try to do something useful as I was going through manual 😃 
I fixed the links in the readme and at the index page of the manual (they didn't work). I also changed links from `juliasymbolics.github.io/SymbolicUtils.jl` to `https://symbolicutils.juliasymbolics.org`. Not sure whether it's the right way. I see the pages are in `PkgPage.jl` and it said to edit index.md directly.
I think it will be easier for first time contributors (such as me) if it was written what are the docs/pages built in. It says "Website built with Franklin.jl." at the bottom of the page, but I've found that PkgPage.jl is used only after looking at CI and gh-pages branch. So I added PkgPage.jl with link to "Website built with..." part in the footer.

Small page/manual link fixes

---

src/types.jl

```julia
julia> using Symbolics
julia> @variables α
(α,)
julia> (2 + exp(α)^2 + 2exp(α))*exp(α)*exp(exp(α))
exp(α)*(2 + exp(α)^2 + 2exp(α))*exp(exp(α))
```
Fixes #232

Less parens in printing

---

src/types.jl

At the risk of completely misunderstanding what this function is supposed to do, the current behavior will always return the default value if the metadata is a Dict, as is the result of calling setmetadata on a symbol without any previous metadata. I don't see any code that sets the metadata to a Ref, but I could be completely wrong.

hopefully fix getemetadata default

---

src/types.jl

Fixes this use case:
```
julia> using Symbolics
julia> @variables x
(x,)
julia> R = [1/x -1/x ; 1 1]
2×2 Matrix{Num}:
x^-1  -(x^-1)
1        1
julia> simplify.(inv(R))
2×2 Matrix{Num}:
x*(1 - (2^-1))  2^-1
-x*(2^-1)  2^-1
julia> simplify.(simplify.(inv(R)) * R)
2×2 Matrix{Num}:
1  2^-1 - (1 - (2^-1))
0                    1
```
It would be nice if that last simplify could deal with the literals...
Fixes #244.

Fix domain error in Mul with literal base and power

---

src/types.jl

Also makes printing less verbose when the coefficient/power on a given term is one.
Before:
```
3 + x + 5y
+
├─ (*)
│  ├─ x
│  └─ 1
└─ (*)
├─ y
└─ 5
2x*(y^-1)
*
├─ (^)
│  ├─ x
│  └─ 1
└─ (^)
├─ y
└─ -1
```
After:
```
3 + x + 5y
+
├─ 3
├─ x
└─ (*)
├─ y
└─ 5
2x*(y^-1)
*
├─ 2
├─ x
└─ (^)
├─ y
└─ -1
```

Make print_tree show coefficients for Add and Mul

---

Project.toml
src/methods.jl
src/types.jl
test/basics.jl

This is good for everyone's health.

make number methods defined only on Symbolic{<:Number}

---

src/types.jl

Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/129
```julia
using MeshCat
using ModelingToolkit
using TORA
using RigidBodyDynamics
using Symbolics
import SymPy
function setup(vis, n_dof, sympy=false)
robot = create_robot_kuka_iiwa_14(vis)
x = MechanismState{sympy ? SymPy.Sym : Num}(robot.mechanism)
q = configuration(x)
if sympy
for i in 1:n_dof
q[i] = SymPy.symbols("q_$i", real = true)
end
else
for i in 1:n_dof
q[i] = Num(Sym{Real}(Symbol("q$i")))
end
end
return x
end
vis = Visualizer()
```
Symbolics:
```julia
julia> x = setup(vis, 3); @time M = mass_matrix(x);
3.721925 seconds (7.73 M allocations: 462.482 MiB, 2.41% gc time, 99.20% compilation time)
julia> for n in 3:7; x = setup(vis, n); @time M = mass_matrix(x); end
0.006976 seconds (79.61 k allocations: 3.028 MiB)
0.007024 …
```

Specialize `Base.isequal`

---

page/index.md
page/rewrite.md
src/rule.jl

Hi, reading manual and getting myself familiar with SymbolicUtils I've tried to update and fix it a bit. 😉 
- I've added some info about automatic simplification of  in index.md;
- Updated docstring in rule.jl to make sense considering current autosimplification rules;
- Updated and extended rewrite.md file with adjustments for autosimplification, a bit more of verbosity for new users and few more examples.
I've planned to add "walking the tree" section in rewriters, but this PR is already taking too long, so decided to put it off to some other PR.
Please let me know if this makes sense and whether some corrections are necessary.
This should close #258.
PS Please feel free to squash the commits on merge (if it happens), they're a bit untidy, but I didn't know whether any corrections are …

Updates and adjustments for manual, especially rewriters section

---

src/types.jl
test/basics.jl

Fixes https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/149

Fix printing of `^` with negative base

---

src/code.jl
test/code.jl

Fix for https://github.com/JuliaSymbolics/Symbolics.jl/issues/177
I still need to prepare code changes and a PR to use the `inbounds` flag in
- `Symbolics.jl`
- `ModelingToolkit.jl`
Please let me know if I'm forgetting any other project that have to be updated from this change.
Note that the unit test is a little bit awkward. I tried to find a better way of doing it, but the macro expansion adds the source of the macro, making it hard to use the `test_repr` pattern that is in place. Please let me know if there is a better alternative to what I did.

Add missing @inbounds in DestructuredArgs

---

src/api.jl

Currently errors with `ERROR: MethodError: no method matching depwarn(::String)`

Fix polynorm deprecation warning

---

src/matchers.jl
src/rule.jl
test/rulesets.jl

Came up  while matching this:
```julia
using ModelingToolkit
@parameters x t
@variables u(..)
Dx = Differential(x)
rhs = Dx(u(t, x))
r = @rule Differential(x)(u(t,x)) => "yes"
@show r(rhs.val) # nothing
```
But now you can do
```julia
r = @rule $(Differential(x))(u(t,x)) => "yes"
```
and it will match
@emmanuellujan

Allow interpolating in LHS of the rules

---

page/rewrite.md
src/rewriters.jl

Walk really needs the rewriter it works with to have the PassThrough
property. Chain also has this property.
xref #272.

Document the behavior Walk with bare rewriters

---

page/index.md
src/types.jl
test/basics.jl

Extend and document canonical form of `Symbolic{<:Number}`

---

src/api.jl
src/types.jl
test/basics.jl

Fix substitute when using metadata

---

src/code.jl
test/code.jl

Currently, `create_array()` is only implemented for `SArray`s but errors for `MArray`s.

Allow for MArrays

---

src/ordering.jl

useful when dealing with `ArrayOp`s

don't rely on isless to be defined on elements, use hash as fallback

---

src/rule.jl

I've been searching where `success(bindings′, 1)` was coming from inside `src/matchers.jl` for almost an hour. Only by accident, I figured out where it was defined. This PR makes the definition of `success` more explicit and therefore easier to find.

Clarify where `success` is defined

---

src/rule.jl
test/rulesets.jl

Closes #322.
@shashi, I think that it would be good to also test a more complicated rule with the predicate, but I couldn't get it to work. Could you either add it to the PR or give a suggestion?

Add where syntax to rules

---

.github/workflows/DeployPage.yml
Project.toml
docs/src/README.md
page/utils.jl
src/utils.jl
test/runtests.jl

This is just a suggestion. In the Julia library, Documenter.jl is used to verify all the documentation via doctests. This means that Documenter's doctest logic should be quite robust. Since this package has a lot of examples in the docstrings, maybe it is a good idea to run doctests to avoid broken documentation.
EDIT: For example, other packages which also use doctests are [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) and [MCMCChains.jl](https://github.com/TuringLang/MCMCChains.jl).

Add a doctest

---

Project.toml
src/polyform.jl
test/polyform.jl

Previously `A[3]-3` was failing to expand

fix expand for expressions with array indexing

---

src/methods.jl
test/basics.jl

This PR defines ndims() in terms of the type that a symbolic expression represents. That should be correct also for future/custom types.
Broadcast assumes all types are "scalar" until defined otherwise.

ndims() and broadcast() definitions for generic symbolic types

---

src/code.jl

Spotted some typos in the docstring which confused me a little and fixed them here.

fix typos in Func toexpr docstring

---

src/ordering.jl

This is required to make all tests in https://github.com/JuliaSymbolics/Symbolics.jl/pull/483 work.

Added ordering for types

---

src/types.jl

Simple fix.
Before
```julia-repo
>julia @syms a; SymbolicUtils.toterm(a+1)
a
>julia @syms a; SymbolicUtils.toterm(2a)
a
```
Now the function works as intended.

Fix `toterm` bug that omits coeff.

---

src/simplify_rules.jl
test/rulesets.jl

- Brought this up on [discourse](https://discourse.julialang.org/t/should-1-x-1/77529), and relative to issue [437](https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/437#issue-1162808282).
- It basically introduces a new simplification rule that sets, as for the title, the rule 1^x == 1, which should be ok for all x.
- Mathematica enforces it by default, and it seems a good idea to have it here.

added rule for 1^x == 1 in POW_RULES

---

src/types.jl
test/basics.jl

In the docstring of `similarterm`, it says that the return type may be different than `t`.
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/6964c768e76dcbc48ee7b1d58fae481d46caa5a0/src/types.jl#L509-L514
However, the type is directly hard-coded according to `f` in the code.
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/6964c768e76dcbc48ee7b1d58fae481d46caa5a0/src/types.jl#L530-L550

Call `BasicSymbolic` arithmetic operations to construct `similarterm`

---

src/code.jl

The field was renamed in #406. Seen on https://github.com/SciML/ModelingToolkit.jl/pull/2020

fix ERROR: type NameState has no field symbolify

---

src/simplify_rules.jl

The change was tested with the issue's reproducible sample
```julia
julia> @variables x
julia> ∂ₓ = Differential(x)
julia> expr = expand_derivatives(∂ₓ(∂ₓ(max(1,x))))
IfElse.ifelse(1 > x, 0, 0)
julia> simplify(expr)
```
and now we yield a `0` instead of `IfElse.ifelse(1 > x, 0, 0)`

Simplify degenerate ifelse cases. Fix JuliaSymbolics/Symbolics.jl#170

---

src/types.jl

Fix #512
```julia
julia> VERSION
v"1.8.5"
(@v1.8) pkg> st -m Symbolics
Status `~/.julia/environments/v1.8/Manifest.toml`
[0c5d862f] Symbolics v5.0.2
(@v1.8) pkg> st -m SymbolicUtils
Status `~/.julia/environments/v1.8/Manifest.toml`
[d1185830] SymbolicUtils v1.0.3
julia> using Symbolics
julia> @variables y::LiteralReal
1-element Vector{Num}:
y
julia> -y
y
```
A minus sign is missing in the printing result above.
The internal structure of `-y` is
```julia
julia> SymbolicUtils.isterm(Symbolics.value(-y))
true
julia> operation(Symbolics.value(-y))
- (generic function with 507 methods)
julia> arguments(Symbolics.value(-y))
1-element Vector{Any}:
y
```
The printing function dispatched for `-y` is the following one:
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/ba96757121155bc8925977a85 …

Fix printing for term operators that could be both unary and binary

---

src/methods.jl

Add a special method to infer the symtype of a `Base.literal_pow` expression. Should fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/455

`promote_symtype` for `Base.literal_pow`

---

.github/workflows/benchmark_pr.yml
benchmark/Project.toml

This creates a GitHub action that uses AirspeedVelocity.jl to automatically run the `benchmark/benchmarks.jl` file on all submitted PRs, and create a table of the performance measurements. This is useful for catching performance regressions.
I tested it on your benchmarks and seems to work. Although I did have to create a `Project.toml` file in the `benchmark` file because `Metatheory` is imported in the benchmarks.
An example GitHub PR comment is shown here: https://github.com/SymbolicML/DynamicExpressions.jl/pull/27#issuecomment-1525571227

Automatically benchmark PRs

---

src/simplify_rules.jl

fixes #347 
Before
```julia
julia> @btime simplify(z*x)
41.083 μs (511 allocations: 27.11 KiB)
x*z
julia> @btime simplify(z*x+z*y)
252.292 μs (3063 allocations: 159.59 KiB)
z*(x + y)
```
After
```julia
julia> @btime simplify(z*x)
27.458 μs (294 allocations: 16.25 KiB)
x*z
julia> @btime simplify(z*x+z*y)
151.834 μs (1724 allocations: 92.55 KiB)
z*(x + y)
```

Enhancement: avoid applying canonicalizing rules on canonical form

---

src/polyform.jl

I found this in https://github.com/ranocha/BSeries.jl/pull/153 since the CI run failed in some `@test_nowarn` statements with the message
```
┌ Warning: `similarvariable` is deprecated, use `similar_variable` instead.
│   caller = polyize(x::SymbolicUtils.BasicSymbolic{Real}, pvar2sym::Bijections.Bijection{Any, Any}, sym2term::Dict{SymbolicUtils.BasicSymbolic, Any}, vtype::Type, pow::Function, Fs::Type, recurse::Bool) at polyform.jl:149
└ @ SymbolicUtils ~/.julia/packages/SymbolicUtils/Oyu8Z/src/polyform.jl:149
Symbolic coefficients: Test Failed at /cache/build/default-amdci5-2/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/Test/src/Test.jl:863
```

replace deprecated `similarvariable` by `similar_variable`

---

src/code.jl
test/code.jl

This dispatch allows `Symbolics.build_function` to build functions when the targets are Tuples. It includes a test.
This closes the issue [46 in Symbolics](https://github.com/JuliaSymbolics/Symbolics.jl/issues/46). I also made some comments there about it.

Included dispatch to toexpr that creates Tuples correctly

---

Project.toml
src/SymbolicUtils.jl
src/inspect.jl
src/types.jl
test/basics.jl
test/fuzz.jl
test/fuzzlib.jl
test/inspect_output/ex-md.txt
test/inspect_output/ex-nohint.txt
test/inspect_output/ex.txt
test/inspect_output/sub10.txt
test/inspect_output/sub14.txt
test/runtests.jl

Just making it easier to debug and request debug output on errors.

inspect & pluck

---

src/ordering.jl
src/types.jl
test/basics.jl
test/inspect_output/ex-md.txt
test/inspect_output/ex-nohint.txt
test/inspect_output/ex.txt
test/inspect_output/sub14.txt
test/order.jl
test/polyform.jl

```julia
julia> expand((x+y-1)^4)
1 - 4x - 4y + 6(x^2) + 12x*y + 6(y^2) - 4(x^3) - 12(x^2)*y - 12x*(y^2) - 4(y^3) + x^4 + 4(x^3)*y + 6(x^2)*(y^2) + 4x*(y^3) + y^4
```
`arguments` no more uses `<ₑ`; `<ₑ` does still maintain a total order, is tested, and used for simplification in non-canonical cases.

better ordering of terms

---

src/polyform.jl
test/polyform.jl

Fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/968

Fix div with rational numbers to fix simplify_fractions

---

src/types.jl

prevent canonicalization where arguments have metadata

---

src/methods.jl
test/code.jl

NaNMath.pow needs a dispatch to prevent stack overflow with symbolic arguments.

NaNMath.pow fix

---

Project.toml

I ran into issues with SymbolicUtils.jl breaking other packages that I tried using. I just found out that this was because of another package holding back AbstractTrees.jl to 0.3. Since SymbolicUtils.jl seems not to work anymore with that version, the compat should also be removed.

Remove compat with AbstractTrees 0.3

---

src/SymbolicUtils.jl
src/types.jl
src/utils.jl

@0x0f0f0f here are my fixes for #584.

Get tests to pass in new TermInterface

---

docs/src/index.md

Fix broken link on documentation homepage

---

src/code.jl

The original code used `get!` which would initialize `state[t]` to `0` if it didn't exist before incrementing. This is unnecessary as the value is only used for incrementing. Using `get` with a default value of `0` achieves the same result without potential performance overhead.
See the source code for `get`:
https://github.com/JuliaLang/julia/blob/0b4590a5507d3f3046e5bafc007cacbbfc9b310b/base/dict.jl#L545
and for `get!`:
https://github.com/JuliaLang/julia/blob/0b4590a5507d3f3046e5bafc007cacbbfc9b310b/base/dict.jl#L473

Replace `get!` with `get` to avoid unnecessary initialization of state values

---

.github/workflows/Downstream.yml

"Standard" group no longer exists in DataDrivenDiffEq.jl, "Core" looks like a good replacement.

Fix DataDrivenDiffEq.jl downstream test

---

docs/make.jl

Strict is now the default, need to specify exceptiopns instead.

Update documentation generator

---

src/types.jl

This is a change intended in 2.0 but apparently never got tested.

Fix head & arguments accessor functions

---

src/code.jl

This pull request addresses a failing test case encountered in the Symbolics.jl integration test CI https://github.com/JuliaSymbolics/SymbolicUtils.jl/actions/runs/9640298551/job/26624028476?pr=615#step:6:987 in PR https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/615 due to an undefined `maketerm` function at https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/43797eb43b33b8d6b0374eac8cd6f87f94bcf79d/src/code.jl#L766
The CI test was failing with an `UndefVarError: maketerm not defined` error. This occurred because the `maketerm` function, although used, was not explicitly imported within the SymbolicUtils.Code module.
This pull request resolves the issue by explicitly importing the `maketerm` function within the SymbolicUtils.Code module. This ensures that the function is …

Import `maketerm` in SymbolicUtils.Code to resolve `UndefVarError`

---

src/SymbolicUtils.jl

This should essentially fix https://github.com/SciML/ModelingToolkit.jl/issues/2827 . The issue was that istree has been marked as deprecated, but istree is also the same function as iscall, causing Aqua to fail.

Fix faulty istree deprecation

---

src/types.jl
test/basics.jl

`-(-x)` will simplify back to `x` and setting metadata on the simplified result is illegal.
Fixes https://github.com/SciML/ModelingToolkit.jl/issues/2855

Fix metadata prop

---

src/methods.jl

When you hit the error condition in `literal_pow` you get an error with rem2pi in it. That is a copy-paste-edit mistake from a few lines up:
```julia
function Base.rem2pi(x::Symbolic, mode::Base.RoundingMode)
T = symtype(x)
T <: Number ? term(rem2pi, x, mode) : error_f_symbolic(rem2pi, T)
end
```
was probably copied into 
```julia
function Base.literal_pow(::typeof(^), x::Symbolic, ::Val{p}) where {p}
T = symtype(x)
T <: Number ? Base.:^(x, p) : error_f_symbolic(rem2pi, T)
end
```
This PR just fixes the typo.

Fix typo in literal_pow overload

---

src/types.jl
test/basics.jl

This PR addresses the test failure observed in https://github.com/JuliaSymbolics/Symbolics.jl/actions/runs/10335343905/job/28609768547?pr=1196#step:7:582 within PR https://github.com/JuliaSymbolics/Symbolics.jl/pull/1196.
Currently, `maketerm` doesn't correctly handle cases where the input `T` is a `BasicSymbolic{Array}`. This leads to the resulting type being incorrectly changed to `AbstractArray` due to https://github.com/JuliaSymbolics/Symbolics.jl/blob/933757bfd1d04f2097c8ad84140796fb19dc3d91/src/arrays.jl#L437. 
This PR modifies `maketerm` to properly handle `BasicSymbolic{Array}` inputs, ensuring the correct type is maintained. 
However, we should probably refactor [`maketerm`](https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/77951c90da8dc167817344ca15047744a73fd5e0/src/types. …

Fix `maketerm` handling of `BasicSymbolic{Array}`

---

src/types.jl
test/basics.jl

This PR addresses an issue in the `basicsymbolic` function where it incorrectly assumes that the `+` and `*` operations always result in `Add` and `Mul` objects, respectively. 
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/2ec473efe9f01bf9730d5108afc2e5908c6f0cf9/src/types.jl#L589-L600
Currently, when arguments possess metadata, the operations might return a `Term` object instead, as seen in 
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/2ec473efe9f01bf9730d5108afc2e5908c6f0cf9/src/types.jl#L1082-L1083
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/2ec473efe9f01bf9730d5108afc2e5908c6f0cf9/src/types.jl#L1136-L1138
This inconsistency was causing problems in https://github.com/Vaibhavdixit02/SymbolicAnalysis.jl/pull/43#issuecomment-2282773079
This PR corrects …

Fix missing `metadata` when operation and resulting `BasicSymbolic` subtype mismatch

---

src/types.jl

Fixes [this](https://github.com/SciML/ModelingToolkit.jl/actions/runs/10447617309/job/28926807757?pr=2945#step:6:627) ambiguity. The [`ConstructionBase` docs](https://juliaobjects.github.io/ConstructionBase.jl/stable/#ConstructionBase.setproperties) explicitly recommend adding a method to `setproperties` (`setproperties_object` is undocumented internals) and type-annotating `patch::NamedTuple`.

fix: avoid `ConstructionBase.setproperties` ambiguity

---

src/types.jl

According to the linter Aqua.jl, SymbolicsUtils has method ambiguities associated with `isequal` and `promote_symtype`:
```
julia> Aqua.test_ambiguities(SymbolicUtils)
50 ambiguities found. To get a list, set `broken = false`.
Ambiguity #1
isequal(x, ::SymbolicUtils.Symbolic) @ SymbolicUtils ~/.julia/dev/SymbolicUtils/src/types.jl:227
isequal(::Missing, ::Any) @ Base missing.jl:81
Possible fix, define
isequal(::Missing, ::SymbolicUtils.Symbolic)
Ambiguity #2
isequal(::SymbolicUtils.Symbolic, x) @ SymbolicUtils ~/.julia/dev/SymbolicUtils/src/types.jl:226
isequal(::Any, ::Missing) @ Base missing.jl:82
Possible fix, define
isequal(::SymbolicUtils.Symbolic, ::Missing)
```
This PR removes the ambiguities associated with `isequal` by defining the specific methods,
```
Base.isequal(::Missing, …
```

Remove method ambiguity in `isequal(::Symbolic, ::Missing)`.

---

test/basics.jl

Following https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/639
Added tests to verify the current behavior of `isequal` with these types, ensuring that it returns `false` as expected without `MethodError`. These tests enhance the robustness of the test suite and protect against potential regressions in the future.

Test: Add `isequal` tests for `Missing` and `Symbolic` types

---

src/methods.jl
test/basics.jl

I added the method  `adjoint(y::Symbolic{<:Number}) = conj(s)`. 
This is what Julia does for example with `adjoint(1im)`.

adjoint(y::Symbolic{<:Number})

---

test/rulesets.jl

The original test for the `where` clause in rules incorrectly handled the scope of the symbolic variable `a`. Two distinct symbolic variables with the same name were created, leading to unexpected behavior when checking for object equality in the `_f` function.
This PR moves the definition of `_f` inside the `@testset` block, ensuring that it references the same symbolic variable `a` as the rule definition. This correction aligns the test with the intended behavior of the `where` clause.

Fix: Correct Scope of Symbolic Variable in `where` Rule Test

---

test/polyform.jl

This PR resolves an issue where the `@eqtest` macro was being defined multiple times due to an extraneous `include("utils.jl")` line in the test suite.

Fix: Resolve `@eqtest` method redefinition warning

---

src/types.jl
test/basics.jl

Draft while the other PRs in https://github.com/SciML/ModelingToolkit.jl/issues/2910 are written, so that the entire thing can be tested together.

feat: add generic to `FnType` representing type of the function

---

.github/workflows/Documentation.yml
.github/workflows/Downstream.yml
.github/workflows/benchmark_pr.yml
.github/workflows/ci.yml
docs/make.jl
docs/src/manual/rewrite.md
test/runtests.jl

This activate doc tests for current julia version 1.10 and executes them when building the documentation.
It also updates the doctests in `rewrite.md` to work with Documenter.jl.
This should fix #385.

activate doc tests for rewrite.md

---

docs/src/api.md
docs/src/manual/interface.md

This PR addresses an issue where the `@docs` blocks for `symtype` and `promote_symtype` in `interface.md` were not being rendered due to duplication with those in `api.md`.
Changes:
- Removed the duplicate `@docs` blocks for `symtype` and `promote_symtype` from `interface.md`.
- Moved the `@docs` block for `issym` from `interface.md` to `api.md` to keep related documentation together.

Resolve duplicate docstring references

---

.github/workflows/benchmark_pr.yml

This pull request updates the `upload-artifact` action in `.github/workflows/benchmark_pr.yml` from the deprecated v2 to v4.

Chore: Update upload-artifact action to v4 in benchmark_pr.yml

---

Project.toml
src/SymbolicUtils.jl
src/types.jl
test/basics.jl
test/hash_consing.jl
test/runtests.jl

- #614
This PR implements hash consing for `Sym` as the first step towards applying hash consing across SymbolicUtils.jl.
Hash consing enables efficient memory usage and potential performance improvements by ensuring that only one unique copy of a symbolic expression exists in memory.
- A [`WeakValueDict`](https://github.com/twavv/WeakValueDicts.jl) is used to store existing symbolic objects. This choice ensures that symbolic objects without strong references are eligible for garbage collection.
- The `BasicSymbolic` struct is modified to be `mutable` to comply with the requirements of `WeakValueDict` (due to how Julia implements finalizers).
- A new "hash" function, `hash2`, is introduced to incorporate `symtype` into the hash calculation. This approach was chosen over modifying the …

Implement hash consing for `Sym`

---

src/types.jl

The modification eliminates the use of the `(::Type{<:Pow{T}})` syntax to improve clarity.

Renamed `Pow` function for clarity

---

README.md

Some links in the `Readme.md` where still pointing to the old location of the documentation. This changes them to the documentation at [SciML](https://docs.sciml.ai/SymbolicUtils/stable/).

update links to stable documentation at SciML

---

src/types.jl
test/hash_consing.jl

- resolve https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/614
- following https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/658
(UROP under @bowenszhu)

Apply hash consing to all `BasicSymbolic` subtypes

---

Project.toml
src/code.jl
test/code.jl

On the master branch:
```julia
julia> using Symbolics
julia> @variables x y;
julia> Base.remove_linenums!(build_function(x^y, [x, y]))
:(function (ˍ₋arg1,)
begin
(^)(ˍ₋arg1[1], ˍ₋arg1[2])
end
end)
```
With this PR:
```julia
julia> using Symbolics
julia> @variables x y;
julia> Base.remove_linenums!(build_function(x^y, [x, y]))
:(function (ˍ₋arg1,)
begin
(NaNMath.pow)(ˍ₋arg1[1], ˍ₋arg1[2])
end
end)
```

Rewrite `^` with `NaNMath.pow` in nanmath-mode

---

src/types.jl
test/hash_consing.jl

This causes several issues where e.g. if a variable has a default, the metadata of the default is not taken into consideration when hashconsing.
Currently causes several MTK issues which I'm working on resolving.

fix: fix hashconsing not comparing nested metadata and inside expressions

---

src/code.jl
test/cse.jl

This is necessary for CSE on array symbolics represented as `ArrayOp`. It will be tested in Symbolics.jl, since there is no way to reproduce it otherwise.

fix: fix `Code.cse` for different symbolic types

---

src/cache.jl
src/types.jl
test/cache_macro.jl

Close https://github.com/JuliaSymbolics/Symbolics.jl/issues/1470
Close https://github.com/SciML/ModelingToolkit.jl/issues/3447

fix: handle explicit `::Any` annotation in `@cache` macro

---

src/types.jl
test/hash_consing.jl

The absence of this led to `ArrayOp`s with different metadata being considered equal during hashconsing.

fix: implement `isequal_with_metadata` for custom symbolics

---

Project.toml
src/SymbolicUtils.jl
src/types.jl

`WeakKeyDict` didn't actually do anything. The thing being hashconsed was `HashconsingWrapper`, which doesn't have a reference outside of the cache. So it was basically up to the GC how much hashconsing we do.

refactor: return to using `WeakValueDict`

---

src/code.jl

The goals of this PR is make sure, that CSE variables are named in a reproducible way.
Otherwise, built functions are not considered egal which can lead to higher memory usage and hinders type stability in some contexts.
```julia
using Symbolics
@variables x, y, z
formulas = [x, x+y, x+y+z]
f1 = Symbolics.build_function(formulas, [x, y, z]; expression=false, cse=true)
f2 = Symbolics.build_function(formulas, [x, y, z]; expression=false, cse=true)
f1===f2
```

name CSE states in a reproducible way

---

benchmark/benchmarks.jl
src/ordering.jl
test/basics.jl

Profiling indicated that in my use case (symbolic multiplication of several large sparse matrices takes almost 1h) a lot of time is spent in `get_degrees()`.
So this PR is my attempt to make it faster and use less memory:
* some trivial fixes to avoid broadcasting
* extract operator handling into separate routines (`get_degrees(op, expr)`) instead of `if op == + .. elseif op == * end`.
That increases memory footprint by 10%, but also makes it faster by 10% (I guess type inference is improved).
* avoid calling `sorted_arguments()` within `get_degrees()`, as that itself calls `get_degrees()`, so `get_degrees()` gets called multiple times for the same expression.
Instead, `get_degrees()` uses `arguments()` and sorts the list of degrees itself.
* Cache the `get_degrees(getindex, expr)`: that …

Refactor get_degrees() to make it faster

---

docs/src/manual/rewrite.md
src/SymbolicUtils.jl
src/matchers.jl
src/rule.jl
src/simplify_rules.jl
test/rewrite.jl

this pr builds on top of [defslot](https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/749) and extends [negative exponent matching](https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/750). Before this pr julia symbolic rewriting rules had this unfortunate behaviour:
```
julia> @syms a x
(a, x)
julia> rule = @rule sin(~x) + cos(~x) => "yes"
sin(~x) + cos(~x) => 1
julia> arguments(sin(x) + cos(x))
2-element SymbolicUtils.SmallVec{Any, Vector{Any}}:
cos(x)
sin(x)
julia> rule(sin(x)+cos(x)) # doesnt match bc arguments are ordered cos first and then sin
julia> arguments(sin(a) + cos(a))
2-element SymbolicUtils.SmallVec{Any, Vector{Any}}:
sin(a)
cos(a)
julia> rule(sin(a)+cos(a)) # match bc arguments are ordered sin first and then cos
"yes"
```
there was the …

[WIP] Commutative operations and negative exponent match in rules
