- src/rulesets.jl
- src/simplify.jl
- test/rulesets.jl
Fix https://github.com/shashi/SymbolicUtils.jl/issues/23
> Remove multiple_of

- src/rulesets.jl
- test/rulesets.jl
Fixes https://github.com/shashi/SymbolicUtils.jl/issues/25
> Cover x + 2x simplifcation

- src/methods.jl
- src/rulesets.jl
- test/fuzz.jl
- test/runtests.jl
Every CI run will test some random stuff now.
> Enable fuzz tests

- index.md
> enhance docs

- src/SymbolicUtils.jl
- src/simplify.jl
- test/basics.jl
> substitute

- src/matchers.jl
- src/rule_dsl.jl
- src/simplify.jl
> Document "contexts"

- src/rulesets.jl
- src/types.jl
- test/fuzz.jl
- test/fuzzlib.jl
It can now generate Complex (even `Complex{Rational}`), Bool and Rational inputs.
Made 2 sets of tests one boolean, the other numeric. (can give fuzzer a "spec", so we can keep adding other type of tests)
> Improve the fuzzer

- src/types.jl
- test/basics.jl
> fix literal functions with > 2 arguments

- src/rule_dsl.jl
- src/rulesets.jl
- src/simplify.jl
- src/util.jl
Let's clean up how we set up the rulesets in a different PR.
cc @YingboMa
> Check if an expression has trigonometric functions and use a different ruleset

- .github/workflows/deploy.yml
- docs/Project.toml
- docs/api.md
- docs/config.md
- docs/faq.md
- docs/index.md
- docs/interface.md
- docs/utils.jl
copies over docs/ directory into website branch and builds it, in theory.
> Move docs into master

- src/SymbolicUtils.jl
- src/abstractalgebra.jl
- test/fuzz.jl
- test/fuzzlib.jl
- test/nf.jl
some fixes and minor optimization of polynormalize
> MPoly fixes

- src/abstractalgebra.jl
- test/fuzz.jl
- test/nf.jl
completes https://github.com/SciML/ModelingToolkit.jl/pull/494
> make to_mpoly clean up one zero and identity before conversion

- src/methods.jl
define your own new symbolic number type which interacts with all others defined before.
> eval_number_methods on your own types

- src/rewriters.jl
workaround for https://github.com/JuliaLang/julia/issues/37006
> don't specialize Chain for tuples of rewriters

- src/methods.jl
- src/types.jl
- test/fuzzlib.jl
- test/interface.jl
- test/rewrite.jl
- test/rulesets.jl
- test/runtests.jl
to go along with https://github.com/SciML/ModelingToolkit.jl/pull/518
> WIP: updates for MTK migration

- benchmark/benchmarks.jl
- src/methods.jl
- src/ordering.jl
- src/simplify_rules.jl
- src/utils.jl
Solves #134 
cc @YingboMa what do you think?
> Extensible trait-like dispatch for Number methods

- docs/interface.md
Cleaned up some cruft that had accumulated in the `Expr` example.
> Update docs on interfacing

- Project.toml
- src/simplify_rules.jl
- src/utils.jl
- test/rulesets.jl
Fix https://github.com/SciML/ModelingToolkit.jl/issues/630
> Use _isinteger check in power rules

- .gitignore
- Project.toml
- src/ordering.jl
- test/order.jl
> Ensure transitivity in tree ordering

- Project.toml
- src/types.jl
- test/basics.jl
> Fix division and printing

- src/methods.jl
- src/types.jl
> use mapfoldl instead of rec_promote_symtype, fix it on Sym{<:FnType}

- .github/workflows/ci.yml
- Project.toml
- src/types.jl
- test/basics.jl
- test/runtests.jl
caches in more cases than #171
> Hash cache with 0 salt

- src/abstractalgebra.jl
- src/types.jl
- test/basics.jl
- print `-1X` as `-X`, `X + -Y` as `X - Y` etc.
- refactor code to separate + and * printing from the rest.
@dpsanders you may like this.
> Some printing improvements

- .gitattributes
- src/code.jl
- src/methods.jl
- src/utils.jl
- test/basics.jl
- test/code.jl
- Support LArray
-  allow DestructuredArgs in place of Assignments in Let
- Allow recursive DestructuredArgs (LHS of an Assignment)
> Code module improvements

- page/interface.md
- src/abstractalgebra.jl
- src/types.jl
- test/nf.jl
> `similarterm` should optionally take the symtype

- src/code.jl
- test/code.jl
Maybe a better name is `SpawnFetch`?
> Par for parallelism

- README.md
This should help guide people in the right direction.
> Point to Symbolics.jl

- src/types.jl
Positional arguments are used for indices in Symbolics.jl
> Make metadata a keyword

- Project.toml
- src/code.jl
- test/code.jl
Proper fix for https://github.com/JuliaSymbolics/Symbolics.jl/pull/150
> Look up everything in symbolify

- src/api.jl
Follow-up of #229. For context, see [this](https://discourse.julialang.org/t/ann-symbolics-jl-a-modern-computer-algebra-system-for-a-modern-language/56251/104) and [this](https://discourse.julialang.org/t/ann-symbolics-jl-a-modern-computer-algebra-system-for-a-modern-language/56251/132). CC @JeffreySarnoff, @ericphanson, @shashi.
> Sync docstring of simplify() with the actual code

- src/types.jl
Fixes #253, thank you @linwaytin for pointing this out.
> docfix #253

- Project.toml
- src/SymbolicUtils.jl
- src/code.jl
- src/types.jl
- test/basics.jl
- test/fuzzlib.jl
> Formalize canonical form

- page/api.md
- src/SymbolicUtils.jl
- src/abstractalgebra.jl
- src/api.jl
- src/simplify_rules.jl
- test/fuzz.jl
- test/interface.jl
- test/nf.jl
> polynormalize -> expand

- src/methods.jl
- src/simplify_rules.jl
- src/utils.jl
- test/rulesets.jl
> Simplify `conj` and `real` for `::Real`

- src/code.jl
Fixes Zygote on generated code here https://github.com/SciML/DataDrivenDiffEq.jl/issues/54
fixes #270
> create_array fixes

- src/methods.jl
Closes JuliaSymbolics/Symbolics.jl#215.
> Add rational division to number_methods

- src/types.jl
- test/basics.jl
- test/fuzz.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/289
> Preserve rational if possible

- src/abstractalgebra.jl
> Hack to fix vcat with Polynomials

- src/abstractalgebra.jl
Reverts JuliaSymbolics/SymbolicUtils.jl#324
> Revert "Hack to fix vcat with Polynomials"

- src/abstractalgebra.jl
ref https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/issues/169
> fix vect with Polynomials

- src/api.jl
- src/code.jl
- src/types.jl
- test/code.jl
@shashi what do you think about this? It might be a little breaking in the API sense.
> Add sort kwarg in arguments to avoid extra computation

- src/polyform.jl
- src/types.jl
- test/basics.jl
- test/polyform.jl
- test/rulesets.jl
- test/runtests.jl
- test/utils.jl
this is to support `Symbolics.solve_for`
> Some more canonicalization in Div

- src/polyform.jl
- src/types.jl
- test/polyform.jl
```julia
julia> flatten_fraction((1+(1+1/a)/a)/a)
(1 + a + a^2) / (a^3)
```
useful for `iszero`
> `flatten_fraction`

- src/polyform.jl
This should fix this https://github.com/SciML/ModelingToolkit.jl/runs/3509882775#step:6:374
> Make simplify_fractions un-PolyForm terms

- src/polyform.jl
- test/polyform.jl
Fixes https://github.com/JuliaSymbolics/Symbolics.jl/pull/404#issuecomment-939404030
> fix avoidance of exponentiation in simplify_fractions

- src/simplify_rules.jl
- test/polyform.jl
- test/rulesets.jl
```julia
julia> simplify(r*cos(x/2)^2 - r*sin(x/2)^2)
r*cos(x)
julia> simplify(2cos(x)*sin(x))
sin(2x)
```
> add double angle formulas

- src/simplify_rules.jl
- test/rulesets.jl
I think **sin(x)^2-1** and **cos(x)^2-1** in ```TRIG_EXP_RULES``` is not right
Also I add @eqtest for that
> Fix TRIG_EXP_RULES

- src/polyform.jl
fixes https://github.com/JuliaSymbolics/Symbolics.jl/issues/494
> special treatment for negative powers in simplify_fractions

- src/polyform.jl
- test/polyform.jl
> fix expand of zero

- src/methods.jl
- test/basics.jl
> LiteralReal

- src/simplify.jl
it does not appear to be a thing anymore
> remove nonzero_denominators from docstring

- src/methods.jl
Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/827
> Add isfinite

- test/rulesets.jl
This is a unittest for the regression noted in #500.
> Add unittest for LiteralReal simplification

- src/types.jl
Do not use `zip` with. It is slow.
> optimize `isequal`

- src/code.jl
- test/code.jl
> Use NaNMath lowering by default

- Project.toml
Could you please release a new version to publish the fix in #550?
> set version to v1.4.1

- Project.toml
- docs/src/api.md
- docs/src/index.md
- src/SymbolicUtils.jl
- src/code.jl
- src/inspect.jl
- src/interface.jl
- src/matchers.jl
- src/ordering.jl
- src/polyform.jl
- src/rewriters.jl
- src/rule.jl
- src/simplify.jl
- src/simplify_rules.jl
- src/substitute.jl
- src/types.jl
- src/utils.jl
- test/fuzzlib.jl
- test/interface.jl
- test/polyform.jl
- test/runtests.jl
- Fix https://github.com/JuliaSymbolics/Symbolics.jl/issues/1141
- Fix https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/595
> revert TermInterface integration

- Project.toml
- src/interface.jl
- src/polyform.jl
- src/rewriters.jl
- src/rule.jl
- src/substitute.jl
- src/utils.jl
- test/basics.jl
- test/runtests.jl
Should fix depwarns from within.
> similarterm -> maketerm in Walk and PolyForm

- Project.toml
- test/basics.jl
- test/doctest.jl
- test/fuzzlib.jl
- test/order.jl
- test/polyform.jl
- test/rewrite.jl
- test/rulesets.jl
- test/runtests.jl
This PR improves the test suite's reproducibility and isolation by using the SafeTestsets package.
This will be particularly beneficial for 
- #658 
by providing granular, isolated test cases for more robust verification.
> Enhance Reproducibility and Isolation with SafeTestsets

- .github/workflows/Documentation.yml
- .github/workflows/Downstream.yml
- .github/workflows/benchmark_pr.yml
- .github/workflows/ci.yml
This pull request upgrades the `julia-actions/setup-julia` action from v1 to v2.
> Upgrade setup-julia action to v2

- src/types.jl
- test/basics.jl
Close https://github.com/SciML/ModelingToolkit.jl/issues/3487
> fix: fix substituting identity of */+ ignores metadata

- src/cache.jl
- src/types.jl
- test/cache_macro.jl
> fix: fix hashconsed ID collisions due to precompilation

- src/types.jl
- test/basics.jl
Continuation of accidentally closed https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/719.
> fix issue #717

- src/types.jl
Grammar fixes: a -> an, added 'any'
> Grammar fix in error message on types.jl
